import ClusterKit
import Foundation
import SwiftData

/// Recurse into the [MemoryItem]s, dividing until unable to
///
/// Returns clusters of [MemoryItem]s in a hierarchy inside of each cluster
/// the memories are somewhat related
public func getTopics<M: Sequence, T: Sequence>(_ memories: M, existing: T, minSamples: Int, minClusterSize: Int) async -> [TopicItem]
    where M.Element == MemoryItem, T.Element == TopicItem {
    return await getTopicsInternal(memories, existing: existing, minSamples: minSamples, minClusterSize: minClusterSize)
}

/// Generated by Claude Sonnet 5
func getTopicsInternal<M: Sequence, T: Sequence>(
    _ memories: M,
    existing: T,
    parent: TopicItem? = nil,
    minSamples: Int,
    minClusterSize: Int
) async -> [TopicItem]
    where M.Element == MemoryItem, T.Element == TopicItem {
    let memoryItems = Set(memories)
    guard !memoryItems.isEmpty else { return [] }

    let existingArray = Array(existing)
    // User-defined topics are never touched by auto-reconciliation; pass through as-is.
    let userDefinedTopics = existingArray.filter(\.isUserDefined)
    let autoTopics = existingArray.filter { !$0.isUserDefined }

    var topicByID: [PersistentIdentifier: TopicItem] = [:]
    var oldMembers: [PersistentIdentifier: Set<PersistentIdentifier>] = [:]
    for t in autoTopics {
        topicByID[t.id] = t
        oldMembers[t.id] = Set((t.memories ?? []).map(\.id))
    }
    // memoryID -> the auto topic that currently owns it (if any)
    var owner: [PersistentIdentifier: PersistentIdentifier] = [:]
    for (tid, mids) in oldMembers { for m in mids { owner[m] = tid } }

    // --- run HDBSCAN ---
    let memAndEmbeddings = memoryItems.compactMap { m -> MemoryEmbeddingItem? in
        guard let e = m.embedding else { return nil }
        return MemoryEmbeddingItem(memoryID: m.id, embedding: e)
    }
    let rawClusters = await (Task.detached {
        CKHDBSCAN(memAndEmbeddings, minSamples: UInt32(minSamples), minClusterSize: UInt32(minClusterSize)).clusters
    }).value

    // Active (non-noise) clusters, keyed by index, with precomputed member sets.
    let activeClusters: [(idx: Int, members: Set<PersistentIdentifier>)] =
        rawClusters.enumerated()
            .filter { !$0.element.isNoise }
            .map { ($0.offset, Set($0.element.items.map(\.memoryID))) }
    let clusterMembersByIdx = Dictionary(uniqueKeysWithValues: activeClusters.map { ($0.idx, $0.members) })

    // --- Union-Find: link an old topic and a new cluster whenever they share a memory ---
    var uf: [Node: Node] = [:]
    func find(_ n: Node) -> Node {
        var cur = n
        while let p = uf[cur], p != cur { cur = p }
        if let root = uf[n] { uf[n] = root } // light path compression
        return uf[n] ?? n
    }
    func union(_ a: Node, _ b: Node) {
        let ra = find(a), rb = find(b)
        if ra != rb { uf[ra] = rb }
    }
    for t in autoTopics { uf[.topic(t.id)] = .topic(t.id) }
    for c in activeClusters { uf[.cluster(c.idx)] = .cluster(c.idx) }
    for c in activeClusters {
        for m in c.members {
            if let tid = owner[m] { union(.topic(tid), .cluster(c.idx)) }
        }
    }

    var groups: [Node: (topics: [PersistentIdentifier], clusters: [Int])] = [:]
    for t in autoTopics { groups[find(.topic(t.id)), default: ([], [])].topics.append(t.id) }
    for c in activeClusters { groups[find(.cluster(c.idx)), default: ([], [])].clusters.append(c.idx) }

    // --- helpers to keep .parent/.children in sync ---
    func detach(_ topic: TopicItem) {
        topic.parent?.children?.removeAll { $0.id == topic.id }
        if let mem = topic.parent?.memories {
            var parentSet = Set(mem)
            let childSet = topic.memories ?? []
            parentSet.subtract(childSet)
            topic.parent!.memories = Array(parentSet)
        }
    }
    func reparent(_ topic: TopicItem, to newParent: TopicItem?) {
        guard topic.parent?.id != newParent?.id else { return }
        detach(topic)
        topic.parent = newParent
        if let newParent {
            if newParent.children == nil { newParent.children = [] }
            if !newParent.children!.contains(where: { $0.id == topic.id }) {
                newParent.children!.append(topic)
            }
            
            var parentMemorySet: Set<MemoryItem> = if let mem = newParent.memories { Set(mem) } else { Set() }
            for mem in topic.memories ?? [] {
                parentMemorySet.insert(mem)
            }
            newParent.memories = Array(parentMemorySet)
        }
    }

    var topLevelResults: [TopicItem] = userDefinedTopics

    for (_, group) in groups {
        if group.clusters.isEmpty {
            // This topic's members produced no cluster this round (pure noise).
            // Leave it exactly as it was rather than deleting/duplicating it.
            topLevelResults.append(contentsOf: group.topics.map { topicByID[$0]! })
            continue
        }

        // Score every (topic, cluster) pair in this component that actually overlaps.
        var overlap: [(topicID: PersistentIdentifier, clusterIdx: Int, score: Int)] = []
        for tid in group.topics {
            for cidx in group.clusters {
                let score = oldMembers[tid]!.intersection(clusterMembersByIdx[cidx]!).count
                if score > 0 { overlap.append((tid, cidx, score)) }
            }
        }
        overlap.sort { $0.score > $1.score }

        // Greedy max-overlap assignment: each cluster claims the best still-available topic.
        var winnerForCluster: [Int: PersistentIdentifier] = [:]
        var usedTopic: Set<PersistentIdentifier> = []
        for entry in overlap where winnerForCluster[entry.clusterIdx] == nil && !usedTopic.contains(entry.topicID) {
            winnerForCluster[entry.clusterIdx] = entry.topicID
            usedTopic.insert(entry.topicID)
        }

        // Build/update one TopicItem per cluster; remember which need no recursion.
        var clusterTopic: [Int: TopicItem] = [:]
        var skipRecursion: Set<Int> = []
        for cidx in group.clusters {
            let memberIDs = clusterMembersByIdx[cidx]!
            let clusterMemoryItems = memoryItems.filter { memberIDs.contains($0.id) }

            if let winnerID = winnerForCluster[cidx], let winner = topicByID[winnerID] {
                if oldMembers[winnerID] == memberIDs {
                    skipRecursion.insert(cidx) // truly unchanged: no new members below this point
                } else {
                    winner.memories = Array(clusterMemoryItems)
                    winner.modification = .now
                }
                clusterTopic[cidx] = winner
            } else {
                clusterTopic[cidx] = TopicItem(name: nil, memories: Array(clusterMemoryItems), parent: parent)
            }
        }

        // Reparent every non-winning old topic under whichever cluster-topic it overlaps most.
        for tid in group.topics where !usedTopic.contains(tid) {
            let loser = topicByID[tid]!
            let best = overlap.filter { $0.topicID == tid }.max { $0.score < $1.score }
            let newParent = best.flatMap { clusterTopic[$0.clusterIdx] }
                ?? group.clusters.compactMap { clusterTopic[$0] }.first
            reparent(loser, to: newParent)
        }

        // Recurse into each cluster-topic, seeding `existing` with its own previous
        // children PLUS anything just reparented under it above.
        for cidx in group.clusters {
            let topic = clusterTopic[cidx]!
            topLevelResults.append(topic)
            if skipRecursion.contains(cidx) { continue }

            let memberIDs = clusterMembersByIdx[cidx]!
            let clusterMemoryItems = memoryItems.filter { memberIDs.contains($0.id) }
            let childrenTopics = await getTopicsInternal(
                clusterMemoryItems,
                existing: topic.children ?? [],
                parent: topic,
                minSamples: minSamples,
                minClusterSize: minClusterSize
            )
            topic.children = childrenTopics
        }
    }

    return topLevelResults.filter { $0.parent == parent }
}

enum Node: Hashable { case topic(PersistentIdentifier), cluster(Int) }

public nonisolated struct MemoryEmbeddingItem: CKFloatArrayCovertible, Sendable {
    public let memoryID: MemoryItem.ID
    public let embedding: [Float]

    public var floatArray: [Float] { embedding }

    public init(memoryID: MemoryItem.ID, embedding: [Float]) {
        self.memoryID = memoryID
        self.embedding = embedding
    }
}
